export const dealProducts = [
  {
    label: "new",
    labelClass: "new",
    category: "T-shirt",
    sizes: ["s", "m", "xl"],
    title: "Cotton fabric T-shirt",
    mainImg: "17.jpg",
    hoverImg: "18.jpg",
    price: "$120",
    oldPrice: "$130",
    colors: [
      { color: "#de8abc", src: "19.jpg", hover: "20.jpg" },
      { color: "#5e68ce", src: "21.jpg", hover: "22.jpg" },
      { color: "#eee", src: "17.jpg", hover: "18.jpg" },
    ],
  },
  {
    label: "Sale",
    labelClass: "sale",
    category: "T-shirt",
    sizes: ["s", "m", "xl"],
    title: "Cotton fabric T-shirt",
    mainImg: "23.jpg",
    hoverImg: "24.jpg",
    price: "$120",
    oldPrice: "$130",
    colors: [
      { color: "#de8abc", src: "19.jpg", hover: "20.jpg" },
      { color: "#a14f3b", src: "23.jpg", hover: "24.jpg" },
    ],
  },
  {
    label: "trending",
    labelClass: "trending",
    category: "T-shirt",
    sizes: ["s", "m", "xl"],
    title: "Cotton fabric T-shirt",
    mainImg: "5.jpg",
    hoverImg: "6.jpg",
    price: "$120",
    oldPrice: "$130",
    colors: [
      { image: "bg/5.jpg", src: "5.jpg", hover: "5.jpg", active: true },
      { image: "bg/6.jpg", src: "6.jpg", hover: "6.jpg" },
      { color: "#e97e70", src: "7.jpg", hover: "7.jpg" },
      { color: "#70e98a", src: "8.jpg", hover: "8.jpg" },
    ],
  },
  {
    category: "Shoes",
    sizes: ["7", "8", "10"],
    title: "Special sport shoes",
    mainImg: "9.jpg",
    hoverImg: "10.jpg",
    price: "$55",
    wishlistActive: true,
    colors: [
      { color: "#0e0e0e", src: "9.jpg", hover: "9.jpg" },
      { color: "#c54367", src: "10.jpg", hover: "10.jpg" },
    ],
  },
  {
    label: "new",
    labelClass: "new",
    category: "Top",
    sizes: ["s", "m"],
    title: "Cotton fabric Top",
    mainImg: "1.jpg",
    hoverImg: "3.jpg",
    price: "$120",
    oldPrice: "$130",
    colors: [
      { color: "#f3f3f3", src: "1.jpg", hover: "3.jpg", active: true },
      { color: "#e8c2ff", src: "2.jpg", hover: "4.jpg" },
    ],
  },
  {
    label: "sale",
    labelClass: "sale",
    category: "watches",
    title: "Mantu smart watch",
    mainImg: "11.jpg",
    hoverImg: "12.jpg",
    price: "$955",
    oldPrice: "$999",
    colors: [
      { color: "#f3f3f3", src: "11.jpg", hover: "12.jpg" },
      { color: "#242424", src: "12.jpg", hover: "11.jpg" },
    ],
  },
  {
    label: "20% off",
    labelClass: "discount",
    category: "belt",
    title: "Mantu leather belt",
    mainImg: "13.jpg",
    hoverImg: "14.jpg",
    price: "$10",
    oldPrice: "$12",
    colors: [
      { color: "#d48a5b", src: "13.jpg", hover: "14.jpg" },
      { color: "#242424", src: "14.jpg", hover: "13.jpg" },
    ],
  },
  {
    category: "Bag",
    sizes: ["m", "l"],
    title: "Leather bag",
    mainImg: "15.jpg",
    hoverImg: "16.jpg",
    price: "$66",
    colors: [
      { color: "#b75956", src: "15.jpg", hover: "16.jpg" },
      { color: "#0e0e0e", src: "16.jpg", hover: "15.jpg" },
    ],
  },
];