export const crudResources = {
  products: {
    title: "Products",
    apiPath: "/products",
    createPath: "/admin/products/create",
    columns: ["title", "category", "price", "stock", "isFeatured", "isActive"],
    fields: [
      { name: "title", label: "Title", type: "text", required: true },
      { name: "slug", label: "Slug", type: "text" },
      { name: "info", label: "Info", type: "textarea" },
      { name: "category", label: "Category", type: "text", required: true },
      { name: "sizes", label: "Sizes", type: "tags", placeholder: "s, m, xl" },
      { name: "mainImg", label: "Main Image", type: "media", folder: "products", required: true },
      { name: "hoverImg", label: "Hover Image", type: "media", folder: "products" },
      { name: "gallery", label: "Gallery", type: "media-list", folder: "products" },
      { name: "price", label: "Price", type: "number", required: true },
      { name: "oldPrice", label: "Old Price", type: "number" },
      { name: "stock", label: "Stock", type: "number", required: true },
      { name: "label", label: "Label", type: "text" },
      { name: "labelClass", label: "Label Class", type: "text" },
      { name: "rating", label: "Rating", type: "number" },
      { name: "discountPercent", label: "Discount Percent", type: "number" },
      { name: "dealEndDate", label: "Deal End Date", type: "datetime-local" },
      { name: "isNewArrival", label: "New Arrival", type: "checkbox" },
      { name: "isDeal", label: "Deal", type: "checkbox" },
      { name: "isFeatured", label: "Featured", type: "checkbox" },
      { name: "isTrending", label: "Trending", type: "checkbox" },
      { name: "isActive", label: "Active", type: "checkbox", defaultValue: true },
    ],
  },
  categories: {
    title: "Categories",
    apiPath: "/categories",
    createPath: "/admin/categories/create",
    columns: ["name", "section", "slug", "sortOrder", "isActive"],
    fields: [
      { name: "name", label: "Name", type: "text", required: true },
      { name: "slug", label: "Slug", type: "text" },
      { name: "section", label: "Section", type: "text", required: true },
      { name: "image", label: "Image", type: "media", folder: "categories" },
      {
        name: "subcategories",
        label: "Subcategories",
        type: "tags",
        placeholder: "T-Shirts, Shirts, Gowns",
      },
      { name: "sortOrder", label: "Sort Order", type: "number" },
      { name: "isActive", label: "Active", type: "checkbox", defaultValue: true },
    ],
  },
  coupons: {
    title: "Coupons",
    apiPath: "/coupons",
    createPath: "/admin/coupons/create",
    columns: ["code", "discountType", "discountValue", "usageLimit", "usedCount", "isActive"],
    fields: [
      { name: "code", label: "Code", type: "text", required: true },
      {
        name: "discountType",
        label: "Discount Type",
        type: "select",
        required: true,
        options: ["percentage", "fixed"],
        defaultValue: "percentage",
      },
      { name: "discountValue", label: "Discount Value", type: "number", required: true },
      { name: "minOrderAmount", label: "Minimum Order Amount", type: "number" },
      { name: "maxDiscountAmount", label: "Maximum Discount Amount", type: "number" },
      { name: "usageLimit", label: "Usage Limit", type: "number" },
      { name: "expiresAt", label: "Expires At", type: "datetime-local", required: true },
      { name: "isActive", label: "Active", type: "checkbox", defaultValue: true },
    ],
  },
  banners: {
    title: "Banners",
    apiPath: "/banners",
    createPath: "/admin/banners/create",
    columns: ["title", "position", "buttonText", "sortOrder", "isActive"],
    fields: [
      { name: "title", label: "Title", type: "text", required: true },
      { name: "subtitle", label: "Subtitle", type: "text" },
      { name: "text", label: "Text", type: "textarea" },
      { name: "image", label: "Image", type: "media", folder: "banners" },
      { name: "buttonText", label: "Button Text", type: "text" },
      { name: "buttonLink", label: "Button Link", type: "text" },
      {
        name: "position",
        label: "Position",
        type: "select",
        options: ["home-top", "home-middle", "home-bottom", "shop", "product-page"],
        defaultValue: "home-middle",
      },
      { name: "className", label: "Class Name", type: "text" },
      { name: "sortOrder", label: "Sort Order", type: "number" },
      { name: "isActive", label: "Active", type: "checkbox", defaultValue: true },
    ],
  },
  heroSlides: {
    title: "Hero Slides",
    apiPath: "/hero-slides",
    createPath: "/admin/hero-slides/create",
    columns: ["title", "subtitle", "discount", "sortOrder", "isActive"],
    fields: [
      { name: "title", label: "Title", type: "text", required: true },
      { name: "subtitle", label: "Subtitle", type: "text" },
      { name: "discount", label: "Discount", type: "text" },
      { name: "text", label: "Text", type: "textarea" },
      { name: "buttonText", label: "Button Text", type: "text" },
      { name: "buttonLink", label: "Button Link", type: "text" },
      { name: "image", label: "Image", type: "media", folder: "hero" },
      { name: "className", label: "Class Name", type: "text" },
      { name: "sortOrder", label: "Sort Order", type: "number" },
      { name: "isActive", label: "Active", type: "checkbox", defaultValue: true },
    ],
  },
};
